# Generated by Django 5.2.1 on 2025-05-26 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='created_at',
        ),
    ]
