# Generated by Django 5.2.1 on 2025-05-26 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0002_remove_teams_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='role',
            field=models.CharField(default='blogger'),
        ),
        migrations.DeleteModel(
            name='roles',
        ),
    ]
