# Generated by Django 5.2.1 on 2025-06-04 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_userblog_team'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
