# Generated by Django 5.2.1 on 2025-05-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='permissions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='read_level',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='write_level',
            field=models.IntegerField(default=0),
        ),
    ]
