# Generated by Django 5.2.1 on 2025-05-27 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0002_post_permissions_post_read_level_post_write_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='read_level',
        ),
        migrations.RemoveField(
            model_name='post',
            name='write_level',
        ),
    ]
