# Generated by Django 5.2.1 on 2025-05-28 19:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0004_comments_likes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='userb',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='likes',
            old_name='userb',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together={('post', 'user')},
        ),
    ]
