# Generated by Django 5.2.1 on 2025-05-28 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Post', '0006_likes_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='liked',
        ),
    ]
